### ISSUE TITLE
[Requirement]  update koa to koa2.0

### ISSUE THREAD

**Issue by fattydevelop** [erha19/weex-debugger#1]
devtool默认的koa依赖依旧为1.0，版本依赖较旧。且koa1.0与2.0的API完全不兼容，在某些情况下（如xnpm指定目录安装，本地项目中存在koa2.0）会默认使用koa2.0，导致devserver无法运行。

**Comment by erha19** [comment]
Next version will update koa to 2.0., thanks~

**Comment by erha19** [comment]
@fattydevelop Already upgrade koa to koa2.0.

**Comment by fattydevelop** [comment]
good job 👍  I'll check it ASAP
