### ISSUE TITLE
AssertionError [ERR_ASSERTION]: Chromium revision is not downloaded. Run "npm install"

### ISSUE THREAD

**Issue by andorcba** [erha19/weex-debugger#4]
执行weex debug时报这个错误，请问怎么解决？

AssertionError [ERR_ASSERTION]: Chromium revision is not downloaded. Run "npm install"

**Comment by xiaohuapunk** [comment]
同样遇到这个问题
![image](https://user-images.githubusercontent.com/9956517/35500310-14d7f154-0511-11e8-8d18-f34729a564a8.png)

**Comment by erha19** [comment]
@andorcba @xiaohuapunk see https://github.com/weexteam/weex-toolkit/issues/275.
